FROM node:12
EXPOSE 3000

WORKDIR /slack-invite-automation

ADD ./entrypoint.sh /usr/local/bin

COPY . /slack-invite-automation

RUN chmod +x /usr/local/bin/entrypoint.sh

USER node

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
