version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/slack-invite-automation
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
