CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.insights (
    id UUID DEFAULT public.uuid_generate_v4() NOT NULL,
    json JSONB NOT NULL,
    type INTEGER DEFAULT NULL,
    trust INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
